### ISSUE TITLE
Error at line 580 of framework/model/MySQLDatabase.php

### ISSUE THREAD

**Issue by reececropley** [dospuntocero/Slideshow#5]
Hey, I am using your module on v3.0.5 of SS.

When I add the extensions in the into the _config.php file I receive the following error:

``` html

Error at line 580 of framework/model/MySQLDatabase.php

```

When I dev/build/?flush=all there are no issues. Its only when i click on the HomePage that the popup in the top right shows this error and the page wont load. Do you know about this error?

The extensions I have installed are: SortableGridField, Sildeshow, cwsoft-foldergallery, dms, silverstripe-event-calender

**Comment by dospuntocero** [comment]
maybe its something else... i cant reproduce it.
